services:
  assessment-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: ${APP_NAME}-app
    volumes:
      - .:/app
    ports:
      - ${GOLANG_PORT}:8080
    depends_on:
      - postgres-assesment
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT} # 5432 untuk internal
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    networks:
      - app-network

  postgres-assesment:
    hostname: postgres
    container_name: ${APP_NAME}-db
    image: postgres:latest
    ports:
      - ${DB_EXTERNAL_PORT:-5450}:5432 # External:Internal
    volumes:
      - app-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - app-network

volumes:
  app-data:

networks:
  app-network:
    driver: bridge
